export const MAX_VIEWPORT_WIDTH = 1920

export const VIEW_HOME = 'HOME'

export const ENTRY_TYPE_IMAGE = 'IMAGE'
export const ENTRY_TYPE_INDIVIDUAL_CHAR = 'INDIVIDUAL_CHAR'
export const ENTRY_TYPE_WORD_LINE = 'WORD_LINE'
export const ENTRY_TYPE_SYMBOL_DOT = 'DOT'
export const ENTRY_TYPE_SYMBOL_CROSS = 'CROSS'

export const DECORATION_TYPE_BORDER = 'BORDER_DECORATION'

export const EVT_HOVER_MENU_ITEM = 'EVT_HOVER_MENU_ITEM'

export const RESOURCE_IMAGE = 'IMAGE'
export const RESOURCE_FONT = 'FONT'

export const FONT_NAME = 'Cousine'

export const TEXTURE_LABEL_ATLAS = 'TEXTURE_LABEL_ATLAS'

export const EVT_ADD_TO_LOAD_QUEUE = 'EVT_ADD_TO_LOAD_QUEUE'
export const EVT_ALLOCATE_TEXTURE = 'EVT_ALLOCATE_TEXTURE'
export const EVT_LOADED_TEXTURES = 'EVT_LOADED_TEXTURES'
export const EVT_TRANSITIONING = 'EVT_TRANSITIONING'
export const EVT_TRANSITIONING_START = 'EVT_TRANSITIONING_START'
export const EVT_TRANSITIONING_END = 'EVT_TRANSITIONING_END'
